# Generated by Django 3.2.10 on 2021-12-17 15:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_alter_dealershiprest_entry_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='dealershiprest',
            name='dealerId',
        ),
        migrations.RemoveField(
            model_name='dealershiprest',
            name='entry_id',
        ),
        migrations.AddField(
            model_name='dealershiprest',
            name='_id',
            field=models.CharField(default='default_id', max_length=100),
        ),
        migrations.AddField(
            model_name='dealershiprest',
            name='_rev',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='dealershiprest',
            name='city',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='dealershiprest',
            name='full_name',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='dealershiprest',
            name='lat',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='dealershiprest',
            name='lon',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='dealershiprest',
            name='short_name',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='dealershiprest',
            name='st',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='dealershiprest',
            name='zip_code',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='dealershiprest',
            name='address',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='dealershiprest',
            name='id',
            field=models.CharField(blank=True, max_length=100, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='dealershiprest',
            name='state',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
