# Generated by Django 3.2.10 on 2021-12-17 16:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_reviewsrest'),
    ]

    operations = [
        migrations.CreateModel(
            name='ReviewRest',
            fields=[
                ('_id', models.CharField(default='default_id', max_length=100)),
                ('_rev', models.CharField(blank=True, max_length=100, null=True)),
                ('id', models.IntegerField(blank=True, max_length=100, primary_key=True, serialize=False)),
                ('name', models.CharField(blank=True, max_length=100, null=True)),
                ('dealership', models.IntegerField(blank=True, max_length=100, null=True)),
                ('review', models.CharField(blank=True, max_length=300, null=True)),
                ('purchase', models.BooleanField(blank=True, null=True)),
                ('purchase_date', models.CharField(blank=True, max_length=100, null=True)),
                ('car_make', models.CharField(blank=True, max_length=100, null=True)),
                ('car_model', models.CharField(blank=True, max_length=100, null=True)),
                ('car_year', models.CharField(blank=True, max_length=100, null=True)),
            ],
        ),
        migrations.DeleteModel(
            name='ReviewsRest',
        ),
    ]
