# Generated by Django 3.2.10 on 2021-12-17 16:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0006_auto_20211217_1607'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reviewrest',
            name='dealership',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
