name: Build and deploy to IBM Cloud Foundry

on: workflow_dispatch

# Environment variables available to all jobs and steps in this workflow
env:
  IBM_CLOUD_REGION: us-south
  IBM_CLOUD_GROUP: default
  IBM_CLOUD_SPACE: dev
  IBM_CLOUD_ORG: ulidder@us.ibm.com
  MANIFEST_NAME: manifest.yml
  IBM_CLOUD_API: ${{secrets.pDbfiOxpPQWV_GD1ytyJzslfERVoa4Z9hTKW8XToKRAa}}

defaults:
  run:
    working-directory: server

jobs:
  setup-build-publish-deploy:
    name: Setup, Build, Publish, and Deploy
    runs-on: ubuntu-latest
